### PR TITLE
New textures and some bugfixes

### PR DESCRIPTION
**Pull request by gr8pefish**
Texture done in the vanilla style.
* 16 x 16
* Red and white as the primary colors
* Limited color palette
* Some shading, but not too much detail

The .png file has also been compressed to save space.

### CODE REVIEW

**Comment by gr8pefish** [comment]
Pictures in-game:
- [In hand](http://i.imgur.com/Yu2WL3u.png)
- [Inventory/JEI](http://i.imgur.com/5U8u6LN.png)

I can also do it in the Unity style (more detail/noise, darker tones) if you'd like. The existing one can also be improved/iterated upon; all I need is feedback!

Let me know what you think.

Thanks,
gr8pefish

**Comment by shadowfacts** [comment]
Nice! Can you update the [model texture](https://github.com/shadowfacts/SleepingBag/blob/1.10.2/src/main/resources/assets/sleepingbag/textures/models/sleepingbag.png) to the red color scheme as well?

**Comment by gr8pefish** [comment]
Yeah sure, it'll just take a minute but I'll get right on it.

**Comment by gr8pefish** [comment]
_6 hours later_ Okay ready whenever now.

**Comment by shadowfacts** [comment]
Awesome, thanks! I'll release a new version once #8 is resolved.

**Comment by gr8pefish** [comment]
Sweet, sounds good. If you add me on the curseforge page I can update the pictures there as well.

**Pull request merged**
